language: go

go:
  - 1.14.4

services:
  - postgresql

before_script:
  - go mod download

env:
  global:
    - PSQL_USER=postgres
    - DATABASE_URL=postgres://postgres@127.0.0.1:5432

script:
  - make test
